language: python
python:
  - "3.6"
  - "3.6-dev"
  - "3.7"
  - "3.7-dev"
dist: xenial
services:
  - xvfb
before_install:
  - sudo apt-get install -y i3
install:
  - pip install -r requirements.txt
before_script:
  - i3
  - sleep 3
script:
  - pytest
