language: python
python:
  - "3.6"
dist: disco
services:
  - xvfb
before_install:
  - sudo apt-get install -y i3 i3status
install:
  - pip install -r requirements.txt
before_script:
  - i3
  - sleep 3
script:
  - pytest
