language: python
python:
  - "3.6"
dist: disco
services:
  - xvfb
before_install:
  - sudo apt-get install -y i3
install:
  - pip install -r requirements.txt
before_script:
  - bash i3
  - sleep 3
script:
  - pytest
