language: python
python:
  - "3.6"
  - "3.6-dev"
  - "3.7"
  - "3.7-dev"
dist: disco
services:
  - xvfb
before_install:
  - sudo apt-get install -y i3 i3status
install:
  - pip install -r requirements.txt
before_script:
  - "i3 &"
  - sleep 3
script:
  - pytest -vv
  - i3-resurrect -h
  - i3-resurrect --help
  - i3-resurrect --version
  - i3-resurrect save -h
  - i3-resurrect save --help
  - i3-resurrect restore -h
  - i3-resurrect restore --help
  - i3-resurrect save -d /tmp/i3-resurrect
  - i3-resurrect save -d /tmp/i3-resurrect --swallow=class,instance,title
  - i3-resurrect save -d /tmp/i3-resurrect --swallow=class,instance,title --layout-only
  - i3-resurrect save -d /tmp/i3-resurrect --swallow=class,instance,title --programs-only
  - i3-resurrect restore -d /tmp/i3-resurrect --programs-only
  - i3-resurrect restore -d /tmp/i3-resurrect --layout-only
